# version:     "0026--11-Sep-2022"
copyright:   "2022"
author:      "bryan273"
name:        "Bryan Tjandra"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/bryan273/os222/"
myloglink:   "/TXT/mylog.txt"
tarballlink: "https://os.vlsm.org/Log/bryan273.tar.bz2.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
